linters:
  enable:
    - usestdlibvars
    - forcetypeassert
    - unconvert
    - unparam
    - execinquery
    - wastedassign
    - exhaustive
    - gosmopolitan
    - goconst
    - gocritic
    - gosimple
    - govet
  disable:
    - ineffassign
